---
title: "Stage 1 muirsam"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(tidyr)
```

```{r message=FALSE}
London <- read_csv("../data/Fixed-London.csv")
```

```{r Clean data, warning=FALSE, eval=FALSE}
#This code chunk is nolonger used and has been integrated to tidy up data r script
# This is code from ZHIXIN's stage 1&2 ---------
posremo <- function(postcode) {
  temp = 0
  for(index in c( 1 : (str_length(postcode)))){
    i = substr(postcode, index, index)
    if(!is.na(as.numeric(i))){
      temp = temp+1
    }
    if(is.na(as.numeric(i)) & temp > 0){
      postcode = str_remove(postcode, i)
    }
  }
  return(postcode)
}

London <- London%>%
  filter(`City/County` == "London")%>%
  separate(`Postal Code` , c("region","subregion"), " ")%>%
  mutate(
    region = map_chr(region, posremo)
  )

central <- c("WC","EC","N1","E1","E2","SE1","SW1","W1","NW1")

subcentral <- c("N6","N19","N7","N4","N5","N16","E5","E8","E9","E3","E14","SE16","SE8","SE14","SE4","SE17","SE15","SE5","SE11","SW4","SW8","SW9","SW11","SW3","SW10","SW5","SW7","W2","W8","W9","W11","NW3","NW5","NW6","NW8")

suburban <- c("N3","N2","N10","N22","N8","N17","N15","E17","E10","E11","E20","E15","E7","E12","E6","E13","E16","SE10","SE7","SE3","SE13","SE6","SE23","SE22","SE24","SE21","SE26","SE27","SW2","SW16","SW12","SW17","SW18","SW6","W6","W14","W12","W10","NW10","NW2","NW11")

London <- London%>%
  mutate(
    large_region = case_when(
      region %in% central ~ "central",
      region %in% subcentral ~ "Middle",
      region %in% suburban ~ "Outer",
      !(region %in% central | region %in% subcentral | region %in% suburban) ~ "Further Outer"
    )
  )

London <- London%>%
  mutate(
    price_per_sq_ft = Price/`Area in sq ft`
  )

#---------------------- From now this is my code

#I want to remove columns 6,7,8
Fixed_London = select(London, -c(7,8))

#I can't seem to get the file to write. I'll try again later
#write_csv(Fixed_London, path = "../data/Fixed-London.csv")


```

```{r message=FALSE}
London %>%
  ggplot(aes(x = `House Type`)) +
  geom_bar() 
```
We can see there are considerably more records of Flats, Houses, New Developments and Penthouses. We don't have enough information on Duplex, Mews or Studios to draw any meaningful conclusions so these records should probably be removed.


```{r message=FALSE}
#Removing duplexes, Mews and Studios
London %>%
  filter(`House Type` %in% c("Flat / Apartment", "House" , "New development" , "Penthouse")) %>%
  ggplot(aes(x = `House Type`)) +
  geom_bar() 
```
```{r message=FALSE}
#Removing duplexes, Mews, Penthouses and Studios and faceting by large region to compare house types (trying to explain how in ZHIXINs plot the further outer region was more expensive then the outer region on average)
London %>%
  filter(`House Type` %in% c("Flat / Apartment", "House" , "New development" )) %>%
  ggplot(aes(x = `House Type`)) +
  geom_bar() +
  facet_wrap(~large_region)
```

```{r message=FALSE}
London %>%
  group_by(`House Type`) %>%
  summarise(
    `Area in sq ft` = mean(`Area in sq ft`),
    Price = mean(Price)
  ) %>%
  arrange(desc(Price))
```
Looking at this information we can see that area per sq ft doesn't seem to affect our data very prominently.

