<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="author" content="TROUT1   Zhixin &amp; Sam &amp; Josh" />
  <meta name="dcterms.date" content="2021-12-02" />
  <title>How Various Factors Affect Housing Prices in London</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="presentation_files/reveal.js-3.3.0.1/css/reveal.css"/>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="presentation_files/reveal.js-3.3.0.1/css/theme/simple.css" id="theme">


  <!-- some tweaks to reveal css -->
  <style type="text/css">
    .reveal h1 { font-size: 2.0em; }
    .reveal h2 { font-size: 1.5em;  }
    .reveal h3 { font-size: 1.25em;	}
    .reveal h4 { font-size: 1em;	}

    .reveal .slides>section,
    .reveal .slides>section>section {
      padding: 0px 0px;
    }



    .reveal table {
      border-width: 1px;
      border-spacing: 2px;
      border-style: dotted;
      border-color: gray;
      border-collapse: collapse;
      font-size: 0.7em;
    }

    .reveal table th {
      border-width: 1px;
      padding-left: 10px;
      padding-right: 25px;
      font-weight: bold;
      border-style: dotted;
      border-color: gray;
    }

    .reveal table td {
      border-width: 1px;
      padding-left: 10px;
      padding-right: 25px;
      border-style: dotted;
      border-color: gray;
    }


  </style>

    <style type="text/css">code{white-space: pre;}</style>


<!-- Printing and PDF exports -->
<script id="paper-css" type="application/dynamic-css">

/* Default Print Stylesheet Template
   by Rob Glazebrook of CSSnewbie.com
   Last Updated: June 4, 2008

   Feel free (nay, compelled) to edit, append, and
   manipulate this file as you see fit. */


@media print {

	/* SECTION 1: Set default width, margin, float, and
	   background. This prevents elements from extending
	   beyond the edge of the printed page, and prevents
	   unnecessary background images from printing */
	html {
		background: #fff;
		width: auto;
		height: auto;
		overflow: visible;
	}
	body {
		background: #fff;
		font-size: 20pt;
		width: auto;
		height: auto;
		border: 0;
		margin: 0 5%;
		padding: 0;
		overflow: visible;
		float: none !important;
	}

	/* SECTION 2: Remove any elements not needed in print.
	   This would include navigation, ads, sidebars, etc. */
	.nestedarrow,
	.controls,
	.fork-reveal,
	.share-reveal,
	.state-background,
	.reveal .progress,
	.reveal .backgrounds {
		display: none !important;
	}

	/* SECTION 3: Set body font face, size, and color.
	   Consider using a serif font for readability. */
	body, p, td, li, div {
		font-size: 20pt!important;
		font-family: Georgia, "Times New Roman", Times, serif !important;
		color: #000;
	}

	/* SECTION 4: Set heading font face, sizes, and color.
	   Differentiate your headings from your body text.
	   Perhaps use a large sans-serif for distinction. */
	h1,h2,h3,h4,h5,h6 {
		color: #000!important;
		height: auto;
		line-height: normal;
		font-family: Georgia, "Times New Roman", Times, serif !important;
		text-shadow: 0 0 0 #000 !important;
		text-align: left;
		letter-spacing: normal;
	}
	/* Need to reduce the size of the fonts for printing */
	h1 { font-size: 28pt !important;  }
	h2 { font-size: 24pt !important; }
	h3 { font-size: 22pt !important; }
	h4 { font-size: 22pt !important; font-variant: small-caps; }
	h5 { font-size: 21pt !important; }
	h6 { font-size: 20pt !important; font-style: italic; }

	/* SECTION 5: Make hyperlinks more usable.
	   Ensure links are underlined, and consider appending
	   the URL to the end of the link for usability. */
	a:link,
	a:visited {
		color: #000 !important;
		font-weight: bold;
		text-decoration: underline;
	}
	/*
	.reveal a:link:after,
	.reveal a:visited:after {
		content: " (" attr(href) ") ";
		color: #222 !important;
		font-size: 90%;
	}
	*/


	/* SECTION 6: more reveal.js specific additions by @skypanther */
	ul, ol, div, p {
		visibility: visible;
		position: static;
		width: auto;
		height: auto;
		display: block;
		overflow: visible;
		margin: 0;
		text-align: left !important;
	}
	.reveal pre,
	.reveal table {
		margin-left: 0;
		margin-right: 0;
	}
	.reveal pre code {
		padding: 20px;
		border: 1px solid #ddd;
	}
	.reveal blockquote {
		margin: 20px 0;
	}
	.reveal .slides {
		position: static !important;
		width: auto !important;
		height: auto !important;

		left: 0 !important;
		top: 0 !important;
		margin-left: 0 !important;
		margin-top: 0 !important;
		padding: 0 !important;
		zoom: 1 !important;

		overflow: visible !important;
		display: block !important;

		text-align: left !important;
		-webkit-perspective: none;
		   -moz-perspective: none;
		    -ms-perspective: none;
		        perspective: none;

		-webkit-perspective-origin: 50% 50%;
		   -moz-perspective-origin: 50% 50%;
		    -ms-perspective-origin: 50% 50%;
		        perspective-origin: 50% 50%;
	}
	.reveal .slides section {
		visibility: visible !important;
		position: static !important;
		width: auto !important;
		height: auto !important;
		display: block !important;
		overflow: visible !important;

		left: 0 !important;
		top: 0 !important;
		margin-left: 0 !important;
		margin-top: 0 !important;
		padding: 60px 20px !important;
		z-index: auto !important;

		opacity: 1 !important;

		page-break-after: always !important;

		-webkit-transform-style: flat !important;
		   -moz-transform-style: flat !important;
		    -ms-transform-style: flat !important;
		        transform-style: flat !important;

		-webkit-transform: none !important;
		   -moz-transform: none !important;
		    -ms-transform: none !important;
		        transform: none !important;

		-webkit-transition: none !important;
		   -moz-transition: none !important;
		    -ms-transition: none !important;
		        transition: none !important;
	}
	.reveal .slides section.stack {
		padding: 0 !important;
	}
	.reveal section:last-of-type {
		page-break-after: avoid !important;
	}
	.reveal section .fragment {
		opacity: 1 !important;
		visibility: visible !important;

		-webkit-transform: none !important;
		   -moz-transform: none !important;
		    -ms-transform: none !important;
		        transform: none !important;
	}
	.reveal section img {
		display: block;
		margin: 15px 0px;
		background: rgba(255,255,255,1);
		border: 1px solid #666;
		box-shadow: none;
	}

	.reveal section small {
		font-size: 0.8em;
	}

}  
</script>


<script id="pdf-css" type="application/dynamic-css">
    
/**
 * This stylesheet is used to print reveal.js
 * presentations to PDF.
 *
 * https://github.com/hakimel/reveal.js#pdf-export
 */

* {
	-webkit-print-color-adjust: exact;
}

body {
	margin: 0 auto !important;
	border: 0;
	padding: 0;
	float: none !important;
	overflow: visible;
}

html {
	width: 100%;
	height: 100%;
	overflow: visible;
}

/* Remove any elements not needed in print. */
.nestedarrow,
.reveal .controls,
.reveal .progress,
.reveal .playback,
.reveal.overview,
.fork-reveal,
.share-reveal,
.state-background {
	display: none !important;
}

h1, h2, h3, h4, h5, h6 {
	text-shadow: 0 0 0 #000 !important;
}

.reveal pre code {
	overflow: hidden !important;
	font-family: Courier, 'Courier New', monospace !important;
}

ul, ol, div, p {
	visibility: visible;
	position: static;
	width: auto;
	height: auto;
	display: block;
	overflow: visible;
	margin: auto;
}
.reveal {
	width: auto !important;
	height: auto !important;
	overflow: hidden !important;
}
.reveal .slides {
	position: static;
	width: 100%;
	height: auto;

	left: auto;
	top: auto;
	margin: 0 !important;
	padding: 0 !important;

	overflow: visible;
	display: block;

	-webkit-perspective: none;
	   -moz-perspective: none;
	    -ms-perspective: none;
	        perspective: none;

	-webkit-perspective-origin: 50% 50%; /* there isn't a none/auto value but 50-50 is the default */
	   -moz-perspective-origin: 50% 50%;
	    -ms-perspective-origin: 50% 50%;
	        perspective-origin: 50% 50%;
}

.reveal .slides section {
	page-break-after: always !important;

	visibility: visible !important;
	position: relative !important;
	display: block !important;
	position: relative !important;

	margin: 0 !important;
	padding: 0 !important;
	box-sizing: border-box !important;
	min-height: 1px;

	opacity: 1 !important;

	-webkit-transform-style: flat !important;
	   -moz-transform-style: flat !important;
	    -ms-transform-style: flat !important;
	        transform-style: flat !important;

	-webkit-transform: none !important;
	   -moz-transform: none !important;
	    -ms-transform: none !important;
	        transform: none !important;
}

.reveal section.stack {
	margin: 0 !important;
	padding: 0 !important;
	page-break-after: avoid !important;
	height: auto !important;
	min-height: auto !important;
}

.reveal img {
	box-shadow: none;
}

.reveal .roll {
	overflow: visible;
	line-height: 1em;
}

/* Slide backgrounds are placed inside of their slide when exporting to PDF */
.reveal section .slide-background {
	display: block !important;
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	z-index: -1;
}

/* All elements should be above the slide-background */
.reveal section>* {
	position: relative;
	z-index: 1;
}

/* Display slide speaker notes when 'showNotes' is enabled */
.reveal .speaker-notes-pdf {
	display: block;
	width: 100%;
	max-height: none;
	left: auto;
	top: auto;
	z-index: 100;
}

/* Display slide numbers when 'slideNumber' is enabled */
.reveal .slide-number-pdf {
	display: block;
	position: absolute;
	font-size: 14px;
}

</script>


<script>
var style = document.createElement( 'style' );
style.type = 'text/css';
var style_script_id = window.location.search.match( /print-pdf/gi ) ? 'pdf-css' : 'paper-css';
var style_script = document.getElementById(style_script_id).text;
style.innerHTML = style_script;
document.getElementsByTagName('head')[0].appendChild(style);
</script>

    <script src="presentation_files/header-attrs-2.11/header-attrs.js"></script>
</head>
<body>
  <div class="reveal">
    <div class="slides">

<section>
    <h1 class="title">How Various Factors Affect Housing Prices in London</h1>
  <h1 class="subtitle"><font size='6'></font></h1>
    <h2 class="author"><font size='8'>TROUT1 <br> Zhixin &amp; Sam &amp; Josh</font></h2>
    <h3 class="date"><font size = '6'>2021-12-02</font></h3>
</section>

<section id="project-goal" class="title-slide slide level1">
<h1>Project Goal</h1>
<p>In this project we will explore how factors such as: Location, House type, Area and Number of Bedrooms influence the price of property in London. The goal of this project is to use this information to identify which factors have the greatest influence on the price of housing.</p>
</section>

<section>
<section id="about-the-data" class="title-slide slide level1">
<h1>About the Data</h1>
<p><font size = '6'>The dataset we used was obtained from Kaggle. According to the uploader the information was obtained via web scraping. Below is what the original data looks like.</font></p>
<pre><code>## Rows: 3,480
## Columns: 11
## $ X                 &lt;int&gt; 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15…
## $ Property.Name     &lt;chr&gt; &quot;Queens Road&quot;, &quot;Seward Street&quot;, &quot;Hotham Road&quot;, &quot;Fest…
## $ Price             &lt;int&gt; 1675000, 650000, 735000, 1765000, 675000, 420000, 14…
## $ House.Type        &lt;chr&gt; &quot;House&quot;, &quot;Flat / Apartment&quot;, &quot;Flat / Apartment&quot;, &quot;Ho…
## $ Area.in.sq.ft     &lt;int&gt; 2716, 814, 761, 1986, 700, 403, 1548, 560, 1308, 646…
## $ No..of.Bedrooms   &lt;int&gt; 5, 2, 2, 4, 2, 1, 4, 1, 3, 2, 6, 6, 5, 2, 2, 6, 3, 6…
## $ No..of.Bathrooms  &lt;int&gt; 5, 2, 2, 4, 2, 1, 4, 1, 3, 2, 6, 6, 5, 2, 2, 6, 3, 6…
## $ No..of.Receptions &lt;int&gt; 5, 2, 2, 4, 2, 1, 4, 1, 3, 2, 6, 6, 5, 2, 2, 6, 3, 6…
## $ Location          &lt;chr&gt; &quot;Wimbledon&quot;, &quot;Clerkenwell&quot;, &quot;Putney&quot;, &quot;Putney&quot;, &quot;Put…
## $ City.County       &lt;chr&gt; &quot;London&quot;, &quot;London&quot;, &quot;London&quot;, &quot;London&quot;, &quot;London&quot;, &quot;L…
## $ Postal.Code       &lt;chr&gt; &quot;SW19 8NY&quot;, &quot;EC1V 3PA&quot;, &quot;SW15 1QL&quot;, &quot;SW15 1LP&quot;, &quot;SW1…</code></pre>
</section>
<section id="problems" class="slide level2">
<h2>Problems</h2>
<p><font size = '6'>There are some large problems with the dataset we need to fix before we begin our analysis.</font></p>
<pre><code>## Rows: 3,480
## Columns: 3
## $ No..of.Bedrooms   &lt;int&gt; 5, 2, 2, 4, 2, 1, 4, 1, 3, 2, 6, 6, 5, 2, 2, 6, 3, 6…
## $ No..of.Bathrooms  &lt;int&gt; 5, 2, 2, 4, 2, 1, 4, 1, 3, 2, 6, 6, 5, 2, 2, 6, 3, 6…
## $ No..of.Receptions &lt;int&gt; 5, 2, 2, 4, 2, 1, 4, 1, 3, 2, 6, 6, 5, 2, 2, 6, 3, 6…</code></pre>
<p><font size = '6'>As you can see, ‘No. of Bedrooms’, ‘No. of Bathrooms’ and ‘No. of Receptions’ are the same as each other in each record. By looking up some of the listings we determined that this number represents the ‘No. of Bedrooms’</font></p>
</section>
<section id="problems-1" class="slide level2">
<h2>Problems</h2>
<pre><code>## Rows: 3,480
## Columns: 1
## $ City.County &lt;chr&gt; &quot;London&quot;, &quot;London&quot;, &quot;London&quot;, &quot;London&quot;, &quot;London&quot;, &quot;London&quot;…</code></pre>
<pre><code>## [1] 962</code></pre>
<p><font size = '6'>We can also see that this dataset contains houses from outside the City of London and that the Location variable does not have entries for 962 of the 3480 listings.</font></p>
</section>
<section id="cleaning" class="slide level2">
<h2>Cleaning</h2>
<p><font size = '6'>- So we cleaned the dataset by: 1. Filtering out all houses that are not in London. 2. Removing the variables “No. of bathrooms” and “No. of receptions.”<sup>2</sup> 3. Creating variable: “price_per_sq_ft” = “Price”/“Area in sq ft” 4. Extracting the District Code from the “Postal Code” variable.<sup>3</sup> 5. Assigning each District code to one of the 4 large regions.<sup>4</sup></p>
<p>Next we will expand on how we assigned each property to one of 4 large regions</font></p>
</section>
<section id="discription-citation" class="slide level2">
<h2>Discription &amp; Citation</h2>
<ul>
<li>All code for tidying the data can be found in r script “presentation/presentation_files/Support-files/Tidy Up Data.R”</li>
</ul>
<h1 style="
font-size: 16pt; 
width: 100%; 
text-align: center
;">
<ol type="1">
<li>Kulkarni, A., 2021. Housing Prices in London. [online] Kaggle.com. <a href="https://www.kaggle.com/arnavkulkarni/housing-prices-in-london" class="uri">https://www.kaggle.com/arnavkulkarni/housing-prices-in-london</a> [Accessed 19 November 2021].</li>
<li>Because of the flaw of the original data, the variable “No. of bedrooms”, “No. of bathrooms”, and "No. of receptions are all the same for each observation. We checked some famous houses and figured out that this number represents the number of bedrooms.</li>
<li>District Code is always the first two to four characters in postal code. i.e: SW9X 9BT has District Code of SW9. This code indicates which region does the house locate.</li>
<li>The standard of dividing regions are shown at next page.</li>
</ol>
</h1>
</section></section>
<section>
<section id="the-closer-the-better" class="title-slide slide level1">
<h1>The Closer, the Better?</h1>
<p>We have chosen to divide the District codes into 4 regions shown on the map below</p>
<ul>
<li>Different marked colour represents different regions:</li>
</ul>
<ol type="1">
<li>Red represents group “A-Central”</li>
<li>Blue represents group “B-Middle”</li>
<li>Red represents group “C-Outer”</li>
<li>Unmarked region represents group “D-Further outer”</li>
</ol>
</section>
<section id="deviding-rule-image" class="slide level2">
<h2>Deviding Rule Image</h2>
<p><img src="presentation_files/Support-files/London_Region_divide.png"  height="500" width="500"></p>
<ul>
<li>What we expected is that: The closer to the city center, the more expensive the house is. That is, higher price per sq ft.</li>
</ul>
</section>
<section id="general-glimpse" class="slide level2">
<h2>General Glimpse</h2>
<p><img src="presentation_files/figure-revealjs/London%20Histrogram-1.png" width="80%" /></p>
</section>
<section id="datainterpretation" class="slide level2">
<h2>Data&amp;Interpretation</h2>
<pre><code>## # A tibble: 4 × 5
##   large_region    `Mean Price` `1/4 Quantile` `Median Price` `3/4 Quantile`
##   &lt;chr&gt;                  &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;
## 1 A-Central              1487.           942.          1223.          1735.
## 2 B-Middle               1212.           841.          1029.          1453.
## 3 C-Outer                 868.           703.           809.           977.
## 4 D-Further Outer         980.           744.           882.          1050.</code></pre>
<p>Surprisingly, we found that the housing price per sq ft is not always decreasing when the region we are looking at is further and further from the city center. When we encounter “D-Further Outer” region, the price increase a little. This happens to mean, median, and quarter quantiles, which means the housing price per sq ft in “Further Outer” region is generally higher than the “Outer” region.</p>
</section>
<section id="mapinterpretation" class="slide level2">
<h2>Map&amp;Interpretation</h2>
<p><font size = '6'>- We are curious if there is a region in “Further Outer” that has a very high housing price per sq ft which is affecting our result. So we made a map to see the distribution of housing price.</font></p>
<p><img src="presentation_files/figure-revealjs/map%20of%20London-1.png" width="80%" /></p>
</section>
<section id="mapinterpretation-1" class="slide level2">
<h2>Map&amp;Interpretation</h2>
<ul>
<li>It seems that no such region exists. The housing price per sq ft in “Further outer” is higher than “Outer” region in general.</li>
</ul>
</section></section>
<section>
<section id="prices-grouped-by-region-and-type-of-housing" class="title-slide slide level1">
<h1>Prices grouped by region and type of housing</h1>
<p>(to look at if the difference in mean price between the outer and further outer regions are concentrated into one type of housing, its not)</p>
<pre><code>## # A tibble: 6 × 4
## # Groups:   House Type [3]
##   `House Type`     large_region    `Area in sq ft`    Price
##   &lt;chr&gt;            &lt;chr&gt;                     &lt;dbl&gt;    &lt;dbl&gt;
## 1 Flat / Apartment D-Further Outer            992. 1064751.
## 2 House            D-Further Outer           2316. 2048030.
## 3 New development  D-Further Outer           1369. 1535955.
## 4 Flat / Apartment C-Outer                    888.  767305.
## 5 House            C-Outer                   2236. 1826378.
## 6 New development  C-Outer                   1325. 1608774.</code></pre>
</section>
<section id="model-showing-correlation-between-price-and-area-over-all-large-regions" class="slide level2">
<h2>Model showing correlation between price and area over all large regions</h2>
<p><img src="presentation_files/figure-revealjs/data%20for%20housetype2-1.png" width="80%" /></p>
</section>
<section id="table-showing-correlation-between-area-and-price-over-all-large-regions" class="slide level2">
<h2>Table showing correlation between Area and Price over all large regions</h2>
<pre><code>## # A tibble: 1 × 12
##   r.squared adj.r.squared    sigma statistic p.value    df  logLik    AIC    BIC
##       &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1     0.575         0.575 1564528.     4020.       0     1 -46606. 93218. 93236.
## # … with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
<p>Due to the Graph being cluttered due to over plotting i instead used glance to create a table to show there is a strong correlation between area and price of housing. We can tell this this from the high adjusted r squared value of 0.575(to 3dp).</p>
</section>
<section id="correlation-between-area-and-price-over-the-middle-region" class="slide level2">
<h2>Correlation between Area and Price over the Middle region</h2>
<p><img src="presentation_files/figure-revealjs/data%20for%20housetype4-1.png" width="80%" /></p>
</section>
<section id="table-showing-correlation-between-area-and-price-over-the-middle-region" class="slide level2">
<h2>Table showing correlation between Area and Price over the Middle region</h2>
<pre><code>## # A tibble: 1 × 12
##   r.squared adj.r.squared  sigma statistic   p.value    df  logLik    AIC    BIC
##       &lt;dbl&gt;         &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1     0.730         0.730 1.23e6     3024. 2.99e-320     1 -17290. 34585. 34600.
## # … with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
<p>The increase in adjusted r squared from 0.575 to 0.730 shows that limiting the data to 1 large region makes the strength of the correlation between area and price much higher.</p>
</section>
<section id="conclusion" class="slide level2">
<h2>Conclusion</h2>
<ul>
<li><p>Generally as you move further from the center of london house prices decrease</p></li>
<li><p>However our data tells us that on average homes in the further outer sector are more expensive then houses in the outer sector , this did not fit with the trend or our hypothesis.</p></li>
<li><p>There is a fairly simplistic linear relationship between area of a home and the price of a home .</p></li>
</ul>
</section>
<section id="limitations-with-our-data" class="slide level2">
<h2>Limitations with our data</h2>
<ul>
<li><p>The data set was poorly webscraped.</p></li>
<li><p>The data set only contained observations from certain regions of London.</p></li>
<li><p>The data set gave limited information on specifics of the properties for example if the houses were terrace, detached or semidetached. As well as if the homes came with any land or any amenities.</p></li>
</ul>
</section></section>
<section id="hello-world" class="title-slide slide level1">
<h1>Hello World</h1>
<ul>
<li><p>Click the <code>Knit</code> button to compile your presentation</p></li>
<li><p>Make sure to commit and push all resulting files to your GitHub repo</p></li>
</ul>
</section>

<section>
<section id="using-reveal.js" class="title-slide slide level1">
<h1>Using reveal.js</h1>
<p>It’s possible to have a horizontal sliding transition as well as nest multiple slides to create a vertical stack.</p>
<p>When presenting, you use the left/right arrows to step through the top-level (horizontal) slides. When you arrive at a vertical stack you can optionally press the up/down arrows to view the vertical slides or skip past them by pressing the right arrow.</p>
<p>(click the down key now)</p>
</section>
<section id="reveal.js" class="slide level2">
<h2>reveal.js</h2>
<ul>
<li><p>The presentation is created using the <code>reveal.js</code> package</p></li>
<li><p>You can create a slide show broken up into sections by using the # and ## heading tags</p></li>
<li><p>You can also create a new slide without a header using a horizontal rule (—-)</p></li>
</ul>
</section>
<section class="slide level2">

<ul>
<li>You can also add pauses between content on a slide using (“. . .”)</li>
</ul>
<div class="fragment">
<p>Like this.</p>
<p>…or using “::: fragment”</p>
<div class="fragment">
<p>Like this.</p>
</div>
</div>
</section></section>
<section id="layouts" class="title-slide slide level1">
<h1>Layouts</h1>
<p>You can use plain text</p>
<ul>
<li>or bullet points</li>
</ul>
<div>
<div style="float: left; width: 50%;">
or text in two columns
</div>
<div style="float: left; width: 50%;">
like this
</div>
</div>
<p>because you can combine HTML and Markdown syntax.</p>
<p style="font-size: 8pt; position: absolute; bottom: -5em; width: 100%; text-align: center;">
*You can also add footnotes
</p>
</section>

<section id="code" class="title-slide slide level1">
<h1>Code</h1>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># a boring regression</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(dist <span class="sc">~</span> speed, <span class="at">data =</span> cars)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)   -17.6      6.76      -2.60 1.23e- 2
## 2 speed           3.93     0.416      9.46 1.49e-12</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(model)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 12
##   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.651         0.644  15.4      89.6 1.49e-12     1  -207.  419.  425.
## # … with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</section>

<section>
<section id="plots" class="title-slide slide level1">
<h1>Plots</h1>
<p><img src="presentation_files/figure-revealjs/plot-iris-1.png" width="80%" /></p>
</section>
<section id="plot-and-text" class="slide level2">
<h2>Plot and text</h2>
<div class="columns">
<div class="column">
<ul>
<li>Some text</li>
<li>goes here</li>
</ul>
</div><div class="column">
<p><img src="presentation_files/figure-revealjs/unnamed-chunk-1-1.png" width="100%" /></p>
</div>
</div>
</section>
<section id="different-widths" class="slide level2">
<h2>Different widths</h2>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li>Some text</li>
<li>goes here</li>
</ul>
</div><div class="column" style="width:60%;">
<p><img src="presentation_files/figure-revealjs/unnamed-chunk-2-1.png" width="100%" /></p>
</div>
</div>
</section></section>
<section id="tables" class="title-slide slide level1">
<h1>Tables</h1>
<p>If you want to generate a table, make sure it is in the HTML format (instead of Markdown or other formats), e.g.,</p>
<table>
<thead>
<tr>
<th style="text-align:right;">
Sepal.Length
</th>
<th style="text-align:right;">
Sepal.Width
</th>
<th style="text-align:right;">
Petal.Length
</th>
<th style="text-align:right;">
Petal.Width
</th>
<th style="text-align:left;">
Species
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
5.1
</td>
<td style="text-align:right;">
3.5
</td>
<td style="text-align:right;">
1.4
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
4.9
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
1.4
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
4.7
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
1.3
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
4.6
</td>
<td style="text-align:right;">
3.1
</td>
<td style="text-align:right;">
1.5
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
3.6
</td>
<td style="text-align:right;">
1.4
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
5.4
</td>
<td style="text-align:right;">
3.9
</td>
<td style="text-align:right;">
1.7
</td>
<td style="text-align:right;">
0.4
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
</tbody>
</table>
</section>

<section>
<section id="images" class="title-slide slide level1">
<h1>Images</h1>
<p><img src="https://images.unsplash.com/photo-1535448033526-c0e85c9e6968?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80" title="Image credit: Photo by Jörg Angeli on Unsplash." alt="Image credit: Photo by Jörg Angeli on Unsplash." width="60%" style="display: block; margin: auto;" /></p>
<p>Or you can also include a full page image. See next slide.</p>
</section>
<section id="section" class="slide level2" data-background-image="https://images.unsplash.com/photo-1535448033526-c0e85c9e6968?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1650&amp;q=80">
<h2 data-background-image="https://images.unsplash.com/photo-1535448033526-c0e85c9e6968?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1650&amp;q=80"></h2>
</section></section>
<section id="math-expressions" class="title-slide slide level1">
<h1>Math Expressions</h1>
<p>You can write LaTeX math expressions inside a pair of dollar signs ($…$), e.g. <span class="math inline">\(\alpha+\beta\)</span>. You can use the display style with double dollar signs:</p>
<p><span class="math display">\[\bar{X}=\frac{1}{n}\sum_{i=1}^nX_i\]</span></p>
</section>

<section id="feeling-adventurous" class="title-slide slide level1">
<h1>Feeling adventurous?</h1>
<p>You can learn more about the options available at the following pages:</p>
<ul>
<li><p><a href="https://github.com/rstudio/revealjs" class="uri">https://github.com/rstudio/revealjs</a></p></li>
<li><p><a href="https://bookdown.org/yihui/rmarkdown/revealjs.html" class="uri">https://bookdown.org/yihui/rmarkdown/revealjs.html</a></p></li>
<li><p><a href="http://www.jenniferbradham.org/post/reveal_js_markdown/" class="uri">http://www.jenniferbradham.org/post/reveal_js_markdown/</a></p></li>
<li><p><a href="https://revealjs.com/" class="uri">https://revealjs.com/</a></p></li>
</ul>
</section>
    </div>
  </div>

  <script src="presentation_files/reveal.js-3.3.0.1/lib/js/head.min.js"></script>
  <script src="presentation_files/reveal.js-3.3.0.1/js/reveal.js"></script>

  <script>

      // Full list of configuration options available at:
      // https://github.com/hakimel/reveal.js#configuration
      Reveal.initialize({
        // Push each slide change to the browser history
        history: true,
        // Vertical centering of slides
        center: false,
        // Transition style
        transition: 'default', // none/fade/slide/convex/concave/zoom
        // Transition style for full page slide backgrounds
        backgroundTransition: 'default', // none/fade/slide/convex/concave/zoom



        // Optional reveal.js plugins
        dependencies: [
        ]
      });
    </script>
  <!-- dynamically load mathjax for compatibility with self-contained -->
  <script>
    (function () {
      var script = document.createElement("script");
      script.type = "text/javascript";
      script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
      document.getElementsByTagName("head")[0].appendChild(script);
    })();
  </script>

<script>
  (function() {
    if (window.jQuery) {
      Reveal.addEventListener( 'slidechanged', function(event) {  
        window.jQuery(event.previousSlide).trigger('hidden');
        window.jQuery(event.currentSlide).trigger('shown');
      });
    }
  })();
</script>


  </body>
</html>
