---
title: "ZHIXIN-map-experiment"
output: html_document
---
```{r install package}
library(tidyverse)
library(tmap)
library(tmaptools)
library(sf)
library(tidyr)
library(leaflet)
library(purrr)
```

```{r warning=FALSE}
London_map <- st_read("ExtraData/CodePointOpen_London_201709.shp", stringsAsFactors = FALSE)

central <- c("WC","EC","N1","E1","E2","SE1","SW1","W1","NW1")

subcentral <- c("N6","N19","N7","N4","N5","N16","E5","E8","E9","E3","E14","SE16","SE8","SE14","SE4","SE17","SE15","SE5","SE11","SW4","SW8","SW9","SW11","SW3","SW10","SW5","SW7","W2","W8","W9","W11","NW3","NW5","NW6","NW8")

suburban <- c("N3","N2","N10","N22","N8","N17","N15","E17","E10","E11","E20","E15","E7","E12","E6","E13","E16","SE10","SE7","SE3","SE13","SE6","SE23","SE22","SE24","SE21","SE26","SE27","SW2","SW16","SW12","SW17","SW18","SW6","W6","W14","W12","W10","NW10","NW2","NW11")

other <- c("NW4","NW7","NW9","N9","N11","N12","N13","N14","N18","N20","N21","E4","E18","SE28","SW18","SE9","SE2","SE12","SE19","SE20","SE25","SW19","SW20","SW13","SW14","SW15","W3","W4","W5","W7","W13")


posremo <- function(postcode) {
  temp = 0
  for(index in c( 1 : (str_length(postcode)))){
    i = substr(postcode, index, index)
    if(!is.na(as.numeric(i))){
      temp = temp+1
    }
    if(is.na(as.numeric(i)) & temp > 0){
      postcode = substr(postcode, 0,index-1)
    }
  }
  return(postcode)
}

cleaned_map <- London_map%>%
  mutate(
    Outward_code = substr(postcode, 0, nchar(postcode)-3),
    District_code = map_chr(Outward_code, posremo)
  )%>%
  filter(
    substr(postcode,0,2) %in% c(central, subcentral, suburban, other) |
    substr(postcode,0,3) %in% c(central, subcentral, suburban, other) |
    substr(postcode,0,4) %in% c(central, subcentral, suburban, other)
  )
```

```{r}
London <- read_csv("Fixed-London.csv")
mean_Price_Dictionary <- London%>%
  group_by(region)%>%
  summarise(
    Mean_Price = mean(price_per_sq_ft)
  )

find_mean_price <- function(District_code){
  result = NA
  for (row in c(1 : nrow(mean_Price_Dictionary))){
    if(mean_Price_Dictionary[row,1] == District_code){
    result = as.numeric(mean_Price_Dictionary[row,2])
    }
  }
  return(result)
}

cleaned_map%>%
  mutate(
    mean_price_per_sqft = map_dbl(District_code, find_mean_price)
  )%>%
  ggplot()+
  geom_sf(aes(colour = mean_price_per_sqft))+
  scale_fill_gradient(low = "black", high = "white")+
  labs(
    title = "Mean Price per sq ft Map of London",
    subtitle = "Gray parts are aera that are missing data",
    legend = "Mean Price per sq ft",
    alt = "Map data from: https://data.london.gov.uk/dataset/ordnance-survey-code-point [Accessed on nov.30 2021]"
  )
```


